Repository capactio/dashboard, pull requests merged in 2022-01, with the labels that each got.

#8 Add catalog, change page layout, ask about input only if needed
  src/App.css
  src/App.tsx
  src/actions/Action.tsx
  src/actions/ActionInputParameters.tsx
  src/generated/graphql.ts
  src/hub/InterfaceGroup.css
  src/hub/InterfaceGroup.graphql
  src/hub/InterfaceGroup.tsx
  src/hub/InterfaceGroups.container.tsx
  src/hub/Interfaces.container.tsx
  src/hub/Interfaces.graphql
  src/hub/InterfacesCard.css
  src/hub/InterfacesCard.tsx
  src/hub/InterfacesList.css
  src/hub/InterfacesList.tsx
  src/layout/Header.tsx
  src/layout/Menu.tsx
  src/layout/NotFound.tsx
  src/layout/Page.css
  src/layout/Page.tsx
  src/routes/actions.tsx
  src/routes/hub-interface-groups.tsx
  src/routes/hub-interfaces.tsx
  src/routes/new-action.tsx
  src/wizard/Wizard.container.tsx
  src/wizard/Wizard.graphql
  src/wizard/Wizard.tsx
  src/wizard/selectActionInterface/SelectActionInterface.container.tsx
  src/wizard/selectActionInterface/SelectActionInterface.tsx
Labels: enhancement, area/dashboard

#11 Get rid of Fluent UI dependency for Action creation form
  package-lock.json
  package.json
  src/layout/Form.css
  src/layout/Form.tsx
  src/wizard/provideActionParameters/InputParametersForm.tsx
  src/wizard/selectActionImplementation/ImplAdditionalInput.tsx
Labels: enhancement, area/dashboard

#10 Introduce login form and Capact look & feel
  .github/workflows/branch-build.yaml
  .github/workflows/pr-build.yaml
  codegen.yml
  package.json
  public/favicon.ico
  public/index.html
  public/logo.svg
  public/logo192.png
  public/logo512.png
  public/logo_white.svg
  public/manifest.json
  src/App.css
  src/App.tsx
  src/actions/Action.container.tsx
  src/actions/Action.graphql
  src/actions/Action.tsx
  src/auth/AuthContext.tsx
  src/auth/LoginForm.css
  src/auth/LoginForm.tsx
  src/auth/RequireAuth.container.tsx
  src/auth/RequireAuth.graphql
  src/generated/graphql.ts
  src/http/connection.ts
  src/http/graphql-fetcher.ts
  src/hub/InterfaceGroup.css
  src/hub/InterfaceGroup.tsx
  src/hub/InterfacesCard.tsx
  src/hub/InterfacesList.tsx
  src/index.css
  src/index.tsx
  src/layout/Header.css
  src/layout/Header.tsx
  src/routes/new-action.tsx
  src/wizard/submitAction/SubmitAction.container.tsx
Labels: enhancement, area/dashboard

#18 Update all dependencies
  package-lock.json
  package.json
Labels: dependencies, security, area/dashboard

#17 Prepare UI for deployment as a part of Capact installation
  README.md
  nginx.conf
  public/config/runtime.js
  public/index.html
  src/actions/Action.container.tsx
  src/actions/ActionList.container.tsx
  src/auth/RequireAuth.container.tsx
  src/config.ts
  src/config/runtime.ts
  src/http/connection.ts
  src/layout/Header.css
  src/layout/Header.tsx
  src/wizard/actionSummary/SelectActionImpl.tsx
Labels: enhancement, area/community, area/dashboard

#20 Add simple release job for Dashboard
  .github/workflows/branch-build.yaml
  .github/workflows/make-release.yaml
  scripts/make-release.sh
Labels: enhancement, area/ci
